### ISSUE TITLE
Define "security posture"

### ISSUE THREAD

**Issue by Zaxim** [MrVaughan/Security-Best-Practices#14]
There should be definitions of some terms that aren't readily apparent, or used specific to this docoument. They should be linked within content.

**Comment by MrVaughan** [comment]
Changed both instance of security posture in readme and home page.

Changed to: 
Don't treat these items as hard and fast rules to tackle all at once, rather over time do your best to improve your overall personal security and privacy by implementing and trying out more of these practices.
