### ISSUE TITLE
Define "risk tolerance"

### ISSUE THREAD

**Issue by Zaxim** [MrVaughan/Security-Best-Practices#15]
There should be definitions of some terms that aren't readily apparent, or used specific to this document. They should be linked within content.

**Comment by MrVaughan** [comment]
Changed use of risk tolerance in opening sentence to be less industry technical. Changed to the following sentence:

Once you have tried many of them out, you can then decide for yourself what your security and privacy needs are compared to the inconvenience and acceptance for the listed threats.
