### ISSUE TITLE
Restructure Backups page

### ISSUE THREAD

**Issue by Zaxim** [MrVaughan/Security-Best-Practices#17]
The https://github.com/MrVaughan/Security-Best-Practices/wiki/Backups page deviates from other pages by calling the heading "Easy Solution" vs. "Solutions."

I get why you did that, as you wanted to call out that this was less than ideal, but it's jarring to the reader. I would change it.

**Comment by MrVaughan** [comment]
Renamed section to solutions and put Option 1 and option 2.
