### ISSUE TITLE
Add iMessage to Chat page

### ISSUE THREAD

**Issue by Zaxim** [MrVaughan/Security-Best-Practices#20]
We talk about iMessage in the SMS page, but maybe we want to mention it in the Chat page? Since it's kind of a hybrid SMS and chat application

**Comment by MrVaughan** [comment]
agreed.

Adding it.

**Comment by MrVaughan** [comment]
Added mention of imessage then added a special not in solution saying that it may not be available for OTR and to see the SMS section for more details
