### ISSUE TITLE
Change Windows page title to PC

### ISSUE THREAD

**Issue by Zaxim** [MrVaughan/Security-Best-Practices#26]
Currently we have a "Mac" page and a "Windows" page. One of them refers to the hardware, while the other one refers to the operating system. I would suggest changing the Windows page to "PC", to be consistent.

I was going to suggest changing the Mac page to OS X, but then realized our target audience might not realize that's the operating system that runs on Macs.

**Comment by MrVaughan** [comment]
updated, well sort of, still use windows a bit throughout the document but not in the heading.
